const spanishKeywordMap = {
    await: 'esperar',
    break: 'romper',
    case: 'caso',
    catch: 'atrapar',
    class: 'clase',
    continue: 'continuar',
    debugger: 'depurador',
    default: 'predeterminado',
    delete: 'eliminar',
    let: 'permitir',
    do: 'hacer',
    else: 'sino',
    export: 'exportar',
    extends: 'extiende',
    false: 'falso',
    finally: 'finalmente',
    for: 'para',
    function: 'función',
    if: 'si',
    import: 'importar',
    in: 'en',
    instanceof: 'instancia de',
    new: 'nuevo',
    null: 'nulo',
    return: 'retornar',
    super: 'super',
    switch: 'interruptor',
    this: 'esto',
    throw: 'lanzar',
    true: 'verdadero',
    try: 'intentar',
    typeof: 'tipo de',
    var: 'var',
    void: 'vacío',
    while: 'mientras',
    with: 'con',
    yield: 'rendimiento',
    length: 'longitud',
    json: 'json'
}

module.exports = { spanishKeywordMap }